import 'package:get/get.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageController extends GetxController {
  var currentLang = 'en'.obs;
  final Map<String, Map<String, String>> _translations = {
    'en': {
      'dashboard': 'Dashboard',
      'meetings': 'Meetings',
      'forums': 'Forums',
      'users': 'Users',
      'profile': 'Profile',
      'logout': 'Sign Out',
      'welcome': 'Welcome Back',
      'overview': 'Overview',
      'start_discussion': 'Start Discussion',
      'schedule_meeting': 'Schedule Meeting',
      'search': 'Search',
      'all_districts': 'All Districts',
      'all_categories': 'All Categories',
      'pending': 'Pending',
      'approved': 'Approved',
      'details': 'Details',
      'responses': 'Responses',
      'post': 'Post',
      'save': 'Save',
      'update_profile': 'Update Profile',
      'change_password': 'Change Password',
      'home': 'Home',
      'updates': 'Updates',
      'announcements': 'Announcements',
      'polls': 'Polls',
      'documents': 'Documents',
      'projects': 'Projects',
      'issues': 'Issues',
      'settings': 'Settings',
      'virtual_meeting': 'Virtual Meeting',
      'system_statistics': 'System Statistics',
      'quick_actions': 'Quick Actions',
      'no_meetings': 'No meetings found',
      'no_forums': 'No forum topics found',
      'no_announcements': 'No announcements yet',
      'no_documents': 'No documents available',
      'no_polls': 'No polls available',
      'no_projects': 'No projects yet',
      'no_issues': 'No issues reported',
      'loading': 'Loading...',
      'retry': 'Retry',
      'cancel': 'Cancel',
      'create': 'Create',
      'delete': 'Delete',
      'edit': 'Edit',
      'save_changes': 'Save Changes',
      'notifications': 'Notifications',
      'mark_all_read': 'Mark all read',
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'create_account': 'Create Account',
      'forgot_password': 'Forgot password?',
      'email': 'Email',
      'password': 'Password',
      'full_name': 'Full Name',
      'phone': 'Phone',
      'district': 'District',
      'description': 'Description',
      'title': 'Title',
      'location': 'Location',
      'date': 'Date',
      'time': 'Time',
      'category': 'Category',
      'status': 'Status',
      'join': 'RSVP Now',
      'join_live': 'Join Live Meeting',
      'cancel_meeting': 'Cancel Meeting',
      'upcoming': 'Upcoming',
      'past': 'Past',
      'ongoing': 'Ongoing',
      'cancelled': 'Cancelled',
      'ended': 'Ended',
      'attendees': 'Attendees',
      'agenda': 'Agenda',
      'comments': 'Comments',
      'post_comment': 'Post Comment',
      'upload': 'Upload',
      'download': 'Download',
      'manage': 'Manage',
      'approve': 'Approve',
      'reject': 'Reject',
      'submit': 'Submit',
      'report_issue': 'Report Issue',
      'new_project': 'New Project',
      'new_announcement': 'New Announcement',
      'new_document': 'New Document',
      'new_meeting': 'New Meeting',
      'new_poll': 'New Poll',
    },
    'so': {
      'dashboard': 'Guddiga',
      'meetings': 'Shirarka',
      'forums': 'Doodaha',
      'users': 'Isticmaalayaasha',
      'profile': 'Profaylka',
      'logout': 'Ka bax',
      'welcome': 'Soo dhawoow',
      'overview': 'Guudmarka',
      'start_discussion': 'Bilow dood',
      'schedule_meeting': 'Jadwal shir',
      'search': 'Raadi',
      'all_districts': 'Degmooyinka oo dhan',
      'all_categories': 'Qaybaha oo dhan',
      'pending': 'La sugayo',
      'approved': 'La ansixiyay',
      'details': 'Faahfaahin',
      'responses': 'Jawaabaha',
      'post': 'Dheji',
      'save': 'Badbaadi',
      'update_profile': 'Cusboonaysii profaylka',
      'change_password': 'Bedel erayga sirta ah',
      'home': 'Guriga',
      'updates': 'Cusboonaysiinta',
      'announcements': 'Ogeysiisyada',
      'polls': "Ra'yiga",
      'documents': 'Dokumentiyada',
      'projects': 'Mashaariicda',
      'issues': 'Arrimaha',
      'settings': 'Dejinta',
      'virtual_meeting': 'Shir virtual ah',
      'system_statistics': 'Tirakoobka nidaamka',
      'quick_actions': 'Ficilada degdega ah',
      'no_meetings': 'Ma jiraan shirar',
      'no_forums': 'Maa jiraan doodood',
      'no_announcements': 'Weli ma jiraan ogeysiisyo',
      'no_documents': 'Ma jiraan dokumentiyo',
      'no_polls': "Ma jiraan ra'yisamo",
      'no_projects': 'Weli ma jiraan mashaariic',
      'no_issues': 'Ma jiraan arrimo la soo sheegay',
      'loading': 'Soconaya...',
      'retry': 'Mar kale day',
      'cancel': 'Jooji',
      'create': 'Abuur',
      'delete': 'Tirtir',
      'edit': 'Tafatir',
      'save_changes': 'Badbaadi isbeddelada',
      'notifications': 'Ogeysiisyada',
      'mark_all_read': 'Dhammaan akhri',
      'sign_in': 'Soo gal',
      'sign_up': 'Isdiiwaangeli',
      'create_account': 'Abuur akoon',
      'forgot_password': 'Erayga sirta ah ee la illaawo?',
      'email': 'Iimaylka',
      'password': 'Erayga sirta ah',
      'full_name': 'Magaca buuxa',
      'phone': 'Telefoonka',
      'district': 'Degmada',
      'description': 'Sharaxaad',
      'title': 'Ciwaanka',
      'location': 'Goobta',
      'date': 'Taariikhda',
      'time': 'Waqtiga',
      'category': 'Qaybta',
      'status': 'Xaaladda',
      'join': 'Ka qaybgal',
      'join_live': 'Ku biir shirka tooska ah',
      'cancel_meeting': 'Jooji shirka',
      'upcoming': 'Soconaya',
      'past': 'Hore',
      'ongoing': 'Socda',
      'cancelled': 'La joojiyay',
      'ended': 'La dhammeeyay',
      'attendees': 'Ka qaybgalayaasha',
      'agenda': 'Ajendaha',
      'comments': 'Faallooyinka',
      'post_comment': 'Dheji faallo',
      'upload': 'Soo geli',
      'download': 'Soo deji',
      'manage': 'Maamul',
      'approve': 'Ansixi',
      'reject': 'Diid',
      'submit': 'Soo gudbi',
      'report_issue': 'Sheeg arrin',
      'new_project': 'Mashruuc cusub',
      'new_announcement': 'Ogeysiis cusub',
      'new_document': 'Dokumenti cusub',
      'new_meeting': 'Shir cusub',
      'new_poll': "Ra'yi cusub",
    },
  };

  String t(String key) {
    return _translations[currentLang.value]?[key] ?? _translations['en']?[key] ?? key;
  }

  Future<void> toggleLanguage() async {
    final newLang = currentLang.value == 'en' ? 'so' : 'en';
    currentLang.value = newLang;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('lang', newLang);
  }

  Future<void> loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    final saved = prefs.getString('lang');
    if (saved != null) {
      currentLang.value = saved;
    }
  }
}
